FROM golang

WORKDIR /app
COPY . .
RUN go get ./...
RUN go build -ldflags "-linkmode external -extldflags -static" -a cmd/youmnibus-capture/youmnibus-capture.go

FROM scratch
COPY --from=0 /app/youmnibus-capture /youmnibus-capture
CMD ["/youmnibus-capture"]
