FROM golang:alpine
RUN apk update && apk add --no-cache git

ENV GOPATH /go
ENV GOBIN /go/bin
ENV CGO_ENABLED 0
WORKDIR /app
RUN mkdir -p /go/bin

COPY ./go.mod .
RUN go mod download
RUN go mod verify

COPY . .
RUN go build ./...
RUN go install ./...
