apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
  namespace: youmnibus
spec:
  assemblyPhase: Success
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1beta2
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: v1
    kind: ServiceAccount
  descriptor:
    description: |-
      RabbitMQ is an open source messaging system that implements the Advanced Message Queueing Protocol to serve a variety of messaging applications.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/rabbitmq/).
      Additional support is available on [community forums](https://groups.google.com/forum/#!forum/rabbitmq-users).
    links:
    - description: 'User Guide: Google Click to Deploy RabbitMQ'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md
    - description: RabbitMQ documentation
      url: https://www.rabbitmq.com/documentation.html
    - description: RabbitMQ Getting Started Tutorials
      url: https://www.rabbitmq.com/getstarted.html
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    notes: |-
      # Get authentication credentials for the cluster

      ```shell
      gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]
      ```
      where:
      * `[CLUSTER_NAME]` is the name of the cluster for this application
      * `[CLUSTER_ZONE]` is the zone, in which the cluster is operating

      Please read [here](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster) for more information.

      <!--- ALL THIS BELOW IS COPIED FROM README.MD -->

      # Get the status of the cluster

      By default, the application does not have an external IP address. To get the
      status of the cluster, use `kubectl` to execute `rabbitmqctl` on the master
      node:

      ```
      kubectl exec -it rabbitmq-rabbitmq-0 --namespace youmnibus -- rabbitmqctl cluster_status
      ```

      # Authorization

      The default username is `rabbit`. Use `kubectl` to get the generated password:

      ```shell
      kubectl get secret/rabbitmq-rabbitmq-secret \
        --namespace youmnibus \
        --output=jsonpath='{.data.rabbitmq-pass}' | base64 --decode
      ```

      # (Optional) Expose the RabbitMQ service externally

      By default, the application does not have an external IP. To create an
      external IP address for the service, run the following command:

      ```
      kubectl patch service/rabbitmq-rabbitmq-svc \
        --namespace youmnibus \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

      > **NOTE:** It might take some time for the external IP to be provisioned.

      # Access RabbitMQ service

      **Option 1:** If you run your RabbitMQ cluster behind a LoadBalancer, run the
      following command to get the external IP of the RabbitMQ service:

      ```
      SERVICE_IP=$(kubectl get service/rabbitmq-rabbitmq-svc \
        --namespace youmnibus \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}:15672"
      ```

      To access the RabbitMQ management UI, open `http://[EXTERNAL-IP]:15672`, where
      `[EXTERNAL-IP]` is the output of the command above.

      **Option 2:** Use port forwarding:

      ```
      kubectl port-forward svc/rabbitmq-rabbitmq-svc --namespace youmnibus 15672
      ```

      To access the RabbitMQ management UI, open [http://127.0.0.1:15672](http://127.0.0.1:15672).

      <!--- ALL THIS ABOVE IS COPIED FROM README.MD -->
    type: RabbitMQ
    version: "3.7"
  info:
  - name: RabbitMQ external IP
    type: Reference
    valueFrom:
      serviceRef:
        name: rabbitmq-rabbitmq-svc
  - name: RabbitMQ username
    value: rabbit
  - name: RabbitMQ password
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-pass
        name: rabbitmq-rabbitmq-secret
  - name: Erlang cookie
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-erlang-cookie
        name: rabbitmq-rabbitmq-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
status:
  components:
  - link: /api/v1/namespaces/youmnibus/configmaps/rabbitmq-deployer-config
    name: rabbitmq-deployer-config
    status: Ready
  - link: /api/v1/namespaces/youmnibus/configmaps/rabbitmq-rabbitmq-config
    name: rabbitmq-rabbitmq-config
    status: Ready
  - link: /api/v1/namespaces/youmnibus/persistentvolumeclaims/rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-0
    name: rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-0
    status: Ready
  - link: /api/v1/namespaces/youmnibus/persistentvolumeclaims/rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-1
    name: rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-1
    status: Ready
  - link: /api/v1/namespaces/youmnibus/persistentvolumeclaims/rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-2
    name: rabbitmq-rabbitmq-pvc-rabbitmq-rabbitmq-2
    status: Ready
  - link: /apis/apps/v1beta2/namespaces/youmnibus/statefulsets/rabbitmq-rabbitmq
    name: rabbitmq-rabbitmq
    status: Ready
  - link: /apis/apps/v1/namespaces/youmnibus/statefulsets/rabbitmq-rabbitmq
    name: rabbitmq-rabbitmq
    status: Ready
  - link: /apis/apps/v1beta1/namespaces/youmnibus/statefulsets/rabbitmq-rabbitmq
    name: rabbitmq-rabbitmq
    status: Ready
  - link: /api/v1/namespaces/youmnibus/secrets/rabbitmq-rabbitmq-secret
    name: rabbitmq-rabbitmq-secret
    status: Ready
  - link: /api/v1/namespaces/youmnibus/services/rabbitmq-rabbitmq-discovery
    name: rabbitmq-rabbitmq-discovery
    status: Ready
  - link: /api/v1/namespaces/youmnibus/services/rabbitmq-rabbitmq-svc
    name: rabbitmq-rabbitmq-svc
    status: Ready
  - link: /api/v1/namespaces/youmnibus/serviceaccounts/rabbitmq-rabbitmq-serviceaccount-661e
    name: rabbitmq-rabbitmq-serviceaccount-661e
    status: Ready
  conditions:
  - lastTransitionTime: "2019-06-22T19:55:07Z"
    lastUpdateTime: "2019-06-22T19:55:07Z"
    message: all components ready
    reason: ComponentsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2019-06-22T19:51:08Z"
    lastUpdateTime: "2019-06-22T19:51:08Z"
    message: No error seen
    reason: NoError
    status: "False"
    type: Error
