---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: youmnibus-query
  namespace: youmnibus
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: youmnibus-query
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      namespace: youmnibus
      labels:
        app: youmnibus-query
    spec:
      containers:
      - name: youmnibus-query
        image: lpulles/youmnibus-query:0.1.6
        env:
        - name: MONGO_HOSTS
          value: "mongod-0.mongodb-service.youmnibus.svc.cluster.local,mongod-1.mongodb-service.youmnibus.svc.cluster.local,mongod-2.mongodb-service.youmnibus.svc.cluster.local"
        - name: MONGO_PORT
          value: "27017"
        - name: MEMCACHE_SUBSCRIBERS_URLS
          value: "memcached-subscribers-memcached-0.memcached-subscribers-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-subscribers-memcached-1.memcached-subscribers-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-subscribers-memcached-2.memcached-subscribers-memcached-svc.youmnibus.svc.cluster.local:11211"
        - name: MEMCACHE_VIDEOS_URLS
          value: "memcached-videos-memcached-0.memcached-videos-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-videos-memcached-1.memcached-videos-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-videos-memcached-2.memcached-videos-memcached-svc.youmnibus.svc.cluster.local:11211"
        - name: MEMCACHE_VIEWS_URLS
          value: "memcached-views-memcached-0.memcached-views-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-views-memcached-1.memcached-views-memcached-svc.youmnibus.svc.cluster.local:11211,memcached-views-memcached-2.memcached-views-memcached-svc.youmnibus.svc.cluster.local:11211"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: youmnibus-query
  namespace: youmnibus
  labels:
    app: youmnibus-query
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: youmnibus-query
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: youmnibus-ingress
  namespace: youmnibus
spec:
  backend:
    serviceName: youmnibus-query
    servicePort: 8080
